/*BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Facultad';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -942 THEN
         DBMS_OUTPUT.PUT_LINE('La tabla Facultad no existe.');
      ELSE
         RAISE;
      END IF;
END;*/


-- Tabla Facultad
CREATE TABLE Facultad (
    id_facultad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_facultad VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255)
);

-- Tabla Sexo
CREATE TABLE Sexo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)
);

CREATE TABLE Ubigeo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)
);

CREATE TABLE Estado_Acta (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)
);

CREATE TABLE Periodo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(6)
);

CREATE TABLE Estado_Alumno (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)
);

-- Tabla Dpto_Academico
CREATE TABLE Dpto_Academico (
    id_dpto_academico NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_dpto VARCHAR2(100) NOT NULL,
    id_facultad NUMBER,
    CONSTRAINT fk_dpto_facultad FOREIGN KEY (id_facultad) REFERENCES Facultad(id_facultad)
);

-- Tabla Escuela
CREATE TABLE Escuela (
    id_escuela NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_escuela VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    id_facultad NUMBER,
    CONSTRAINT fk_escuela_facultad FOREIGN KEY (id_facultad) REFERENCES Facultad(id_facultad)
);

-- Tabla Profesores
CREATE TABLE Profesores (
    id_profesor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    dni CHAR(8) UNIQUE NOT NULL,
    especialidad VARCHAR2(100),
    email VARCHAR2(100) UNIQUE,
    telefono VARCHAR2(20),
    id_dpto_academico NUMBER,
    CONSTRAINT fk_profesor_dpto FOREIGN KEY (id_dpto_academico) REFERENCES Dpto_Academico(id_dpto_academico)
);

CREATE TABLE Dato_Personales (
    id_persona NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    dni CHAR(8) UNIQUE NOT NULL,
    sexo NUMBER,
    ubigeo NUMBER,
    fecha_nacimiento DATE NOT NULL,
    direccion VARCHAR2(255),
    telefono VARCHAR2(20),
    email VARCHAR2(100) UNIQUE,
    CONSTRAINT fk_datos_sexo FOREIGN KEY (sexo) REFERENCES Sexo(id),
    CONSTRAINT fk_datos_ubigeo FOREIGN KEY (ubigeo) REFERENCES Ubigeo(id)
);

CREATE TABLE Alumnos (
    id_alumno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona NUMBER, 
    id_escuela NUMBER,
    id_codigo VARCHAR2(9) UNIQUE PRIMARY KEY,
    estado NUMBER,
    CONSTRAINT fk_alumno_persona FOREIGN KEY (id_persona) REFERENCES Dato_Personales(id_persona),
    CONSTRAINT fk_alumno_escuela FOREIGN KEY (id_escuela) REFERENCES Escuela(id_escuela),
    CONSTRAINT fk_alumno_estado FOREIGN KEY (estado) REFERENCES Estado_Alumno(id)
);

-- Tabla Plan de Estudios
CREATE TABLE Plan_Estudios (
    id_plan NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_plan VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    fecha_creacion DATE,
    id_escuela NUMBER,
    CONSTRAINT fk_plan_escuela FOREIGN KEY (id_escuela) REFERENCES Escuela(id_escuela)
);

-- Tabla Cursos
CREATE TABLE Cursos (
    id_curso NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_curso VARCHAR2(100) NOT NULL,
    codigo_curso VARCHAR2(10) UNIQUE NOT NULL,
    creditos NUMBER(2) NOT NULL,
    id_profesor NUMBER,
    CONSTRAINT fk_curso_profesor FOREIGN KEY (id_profesor) REFERENCES Profesores(id_profesor)
);


CREATE TABLE Seccion (
    id_seccion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_periodo NUMBER,
    id_profesor NUMBER,
    id_curso NUMBER,
    CONSTRAINT fk_seccion_periodo FOREIGN KEY (id_periodo) REFERENCES Periodo(id),
    CONSTRAINT fk_seccion_profesor FOREIGN KEY (id_profesor) REFERENCES Profesores(id_profesor),
    CONSTRAINT fk_seccion_curso FOREIGN KEY (id_curso) REFERENCES Cursos(id_curso)
);

-- Tabla de Requisitos
CREATE TABLE Requisitos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_curso_princ NUMBER,
    id_curso_requer NUMBER, 
    CONSTRAINT fk_req_principal FOREIGN KEY (id_curso_princ) REFERENCES Cursos(id_curso),
    CONSTRAINT fk_req_requerimiento FOREIGN KEY (id_curso_requer) REFERENCES Cursos(id_curso)
)

-- Tabla Cursos_Plan_Estudios (relaciona Cursos y Plan de Estudios)
CREATE TABLE Cursos_Plan_Estudios (
    id_curso NUMBER,
    id_plan NUMBER,
    semestre NUMBER(2) NOT NULL,
    PRIMARY KEY (id_curso, id_plan),
    CONSTRAINT fk_cpe_curso FOREIGN KEY (id_curso) REFERENCES Cursos(id_curso),
    CONSTRAINT fk_cpe_plan FOREIGN KEY (id_plan) REFERENCES Plan_Estudios(id_plan)
);

-- Tabla Matricula (inscripciones de alumnos en cursos)
CREATE TABLE Matricula (
    id_matricula NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_alumno NUMBER,
    id_curso NUMBER,
    semestre_academico VARCHAR2(10) NOT NULL,
    fecha_matricula DATE NOT NULL,
    CONSTRAINT fk_matricula_alumno FOREIGN KEY (id_alumno) REFERENCES Alumnos(id_alumno),
    CONSTRAINT fk_matricula_curso FOREIGN KEY (id_curso) REFERENCES Cursos(id_curso)
);

-- Tabla Acta_Calificacion (calificaciones de alumnos en cursos)
CREATE TABLE Acta_Calificacion (
    id_acta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_alumno NUMBER,
    id_curso NUMBER,
    fecha_evaluacion DATE NOT NULL,
    calificacion NUMBER(4,2) CHECK (calificacion >= 0 AND calificacion <= 20),
    estado NUMBER,
    CONSTRAINT fk_calificacion_alumno FOREIGN KEY (id_alumno) REFERENCES Alumnos(id_alumno),
    CONSTRAINT fk_calificacion_curso FOREIGN KEY (id_curso) REFERENCES Cursos(id_curso),
    CONSTRAINT fk_calificacion_estado FOREIGN KEY (estado) REFERENCES Estado_Acta(id)
);


SELECT * FROM ACTA_CALIFICACION;